name: PowerBoard
version: 3.5.5
author: Xitee
softdepend: [PermissionsEx, Vault, PlaceholderAPI, LuckPerms]
main: de.xite.scoreboard.main.PowerBoard
api-version: 1.13
commands:
   sb:
      description: Manage the plugin
   pb:
      description: Manage the plugin
   powerboard:
      description: Manage the plugin